/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.22).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorModel;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-11-01T18:02:49.240Z[GMT]")
@Api(value = "message", description = "the message API")
public interface MessageApi {

    @ApiOperation(value = "Returns 'I came, I saw, I conquered'", nickname = "getConquestMessage", notes = "Returns conquest message", response = String.class, tags={ "conquest", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Message returned", response = String.class),
        @ApiResponse(code = 200, message = "error payload", response = ErrorModel.class) })
    @RequestMapping(value = "/message",
        produces = { "tex/plain", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> getConquestMessage();

}

